### ISSUE TITLE
Improve furniture system on load to prevent crashing a server on start

### ISSUE THREAD

**Issue by pagoru** [openhotel/openhotel#495]

**Comment by alqubo** [comment]
```
2024-12-26T22:14:22.254776388Z arch: (x86_64)
2024-12-26T22:14:22.764209442Z HJ24-12-26 22:14:22:763 | Version 0.5.9
2024-12-26T22:14:22.764231162Z 24-12-26 22:14:22:764 | OS linux
2024-12-26T22:14:22.764304530Z 24-12-26 22:14:22:764 | Arch x86_64
2024-12-26T22:14:22.764311053Z 24-12-26 22:14:22:764 | Checking for updates...
2024-12-26T22:14:23.049692967Z 24-12-26 22:14:23:049 | Everything is up to date!
2024-12-26T22:14:23.049776376Z 24-12-26 22:14:23:049 | server
2024-12-26T22:14:23.765554074Z error: Uncaught (in promise) Error: Furniture with id teleports@telephone already exists!
2024-12-26T22:14:23.765583400Z     at unzipZipFile (file:///tmp/deno-compile-server_linux/server/src/modules/system/game/furniture.ts:20:48)
2024-12-26T22:14:23.765677849Z     at eventLoopTick (ext:core/01_core.js:175:7)
2024-12-26T22:14:23.765684692Z     at async unzipZipFile (file:///tmp/deno-compile-server_linux/server/src/modules/system/game/furniture.ts:9:90)
2024-12-26T22:14:23.765688819Z     at async Object.load (file:///tmp/deno-compile-server_linux/server/src/modules/system/game/furniture.ts:28:69)
2024-12-26T22:14:23.765703767Z     at async Object.load (file:///tmp/deno-compile-server_linux/server/src/modules/system/game/main.ts:11:5)
2024-12-26T22:14:23.765707735Z     at async Object.load (file:///tmp/deno-compile-server_linux/server/src/modules/system/main.ts:55:5)
```

**Comment by pagoru** [comment]
remove `2024-12-26--00-10-remove-furniture` migration
